export enum ActionTypes {
  SET_PUBLIC_POSTS = '@@posts/SET_PUBLIC_POSTS',
  SET_PRIVATE_POSTS = '@@posts/SET_PRIVATE_POSTS',
  SET_PENDING_POSTS = '@@posts/SET_PENDING_POSTS',
  SET_POST_THEME = '@@posts/SET_POST_THEME',
  SET_POST_VALUE = '@@posts/SET_POST_VALUE',
  PUBLISH_POST_REQUEST = '@@posts/PUBLISH_POST_REQUEST',
  PRIVATE_POST_REQUEST = '@@posts/PRIVATE_POST_REQUEST',
  SET_IS_SEND_POST = '@@posts/SET_IS_SEND_POST',
  CHANGE_PAGE = '@@posts/CHANGE_PAGE'
}
